        (r#"sudo git merge main"#, PolicyGateAction::Merge),
        (r#"sudo /usr/bin/git merge main"#, PolicyGateAction::Merge),
        (r#"env FOO=bar git merge main"#, PolicyGateAction::Merge),
        (r#"env FOO=bar /usr/bin/git merge main"#, PolicyGateAction::Merge),
        (r#"bash -c "git merge main""#, PolicyGateAction::Merge),
        (r#"bash -lc "git merge main""#, PolicyGateAction::Merge),
        (r#"bash -euxo pipefail -c "git merge main""#, PolicyGateAction::Merge),
        (r#"sh -c "git merge main""#, PolicyGateAction::Merge),
        (r#"xargs -I{} git merge main"#, PolicyGateAction::Merge),
        (r#"git -C /repo merge main"#, PolicyGateAction::Merge),
        (r#"git -c core.editor=vim merge main"#, PolicyGateAction::Merge),
        (r#"gh pr merge 42"#, PolicyGateAction::Merge),
        (r#"sudo gh pr merge 42"#, PolicyGateAction::Merge),
        (r#"/usr/bin/gh pr merge 42"#, PolicyGateAction::Merge),
        (r#"kubectl apply -f k8s.yaml"#, PolicyGateAction::Apply),
        (r#"kubectl --context=prod apply -f k8s.yaml"#, PolicyGateAction::Apply),
        (r#"sudo /usr/bin/kubectl -n prod apply -f k8s.yaml"#, PolicyGateAction::Apply),
        (r#"terraform apply"#, PolicyGateAction::Apply),
        (r#"terraform -chdir=infra apply"#, PolicyGateAction::Apply),
        (r#"sudo terraform -chdir infra apply"#, PolicyGateAction::Apply),
        (r#"helm upgrade --install app chart"#, PolicyGateAction::Deploy),
        (r#"sudo helm upgrade --install app chart"#, PolicyGateAction::Deploy),
        (r#"docker push ghcr.io/org/image:latest"#, PolicyGateAction::Deploy),
        (r#"sudo /usr/bin/docker push ghcr.io/org/image:latest"#, PolicyGateAction::Deploy),
        (r#"cargo publish --dry-run"#, PolicyGateAction::Deploy),
        (r#"sudo cargo publish --dry-run"#, PolicyGateAction::Deploy),
        (r#"env FOO=bar docker push ghcr.io/org/image:latest"#, PolicyGateAction::Deploy),
        (r#"env FOO=bar cargo publish --dry-run"#, PolicyGateAction::Deploy),
        (r#"bash -lc "docker push ghcr.io/org/image:latest""#, PolicyGateAction::Deploy),
        (r#"bash -lc "cargo publish --dry-run""#, PolicyGateAction::Deploy),
        (r#"xargs -n 1 docker push ghcr.io/org/image:latest"#, PolicyGateAction::Deploy),
        (r#"xargs -n1 cargo publish --dry-run"#, PolicyGateAction::Deploy),
        (r#"nohup git merge main"#, PolicyGateAction::Merge),
        (r#"nohup docker push img"#, PolicyGateAction::Deploy),
        (r#"nohup terraform apply"#, PolicyGateAction::Apply),
        (r#"timeout 10 git merge main"#, PolicyGateAction::Merge),
        (r#"timeout 10 docker push img"#, PolicyGateAction::Deploy),
        (r#"timeout 10 terraform apply"#, PolicyGateAction::Apply),
        (r#"stdbuf -oL git merge main"#, PolicyGateAction::Merge),
        (r#"stdbuf -oL docker push img"#, PolicyGateAction::Deploy),
        (r#"stdbuf -oL terraform apply"#, PolicyGateAction::Apply),
        (r#"watch -n 1 git merge main"#, PolicyGateAction::Merge),
        (r#"watch -n 1 docker push img"#, PolicyGateAction::Deploy),
        (r#"watch -n 1 terraform apply"#, PolicyGateAction::Apply),
        (r#"time git merge main"#, PolicyGateAction::Merge),
        (r#"time docker push img"#, PolicyGateAction::Deploy),
        (r#"time terraform apply"#, PolicyGateAction::Apply),
        (r#"nice -n 10 git merge main"#, PolicyGateAction::Merge),
        (r#"nice -n 10 docker push img"#, PolicyGateAction::Deploy),
        (r#"nice -n 10 terraform apply"#, PolicyGateAction::Apply),
        (r#"ionice -c 2 git merge main"#, PolicyGateAction::Merge),
        (r#"ionice -c 2 docker push img"#, PolicyGateAction::Deploy),
        (r#"ionice -c 2 terraform apply"#, PolicyGateAction::Apply),
        (r#"env -i git merge main"#, PolicyGateAction::Merge),
        (r#"env -i docker push img"#, PolicyGateAction::Deploy),
        (r#"env -i terraform apply"#, PolicyGateAction::Apply),
        (r#"sudo -E git merge main"#, PolicyGateAction::Merge),
        (r#"sudo -E docker push img"#, PolicyGateAction::Deploy),
        (r#"sudo -E terraform apply"#, PolicyGateAction::Apply),
        (r#"sudo -u root git merge main"#, PolicyGateAction::Merge),
        (r#"sudo -u root docker push img"#, PolicyGateAction::Deploy),
        (r#"sudo -u root terraform apply"#, PolicyGateAction::Apply),
        (r#"doas git merge main"#, PolicyGateAction::Merge),
        (r#"doas docker push img"#, PolicyGateAction::Deploy),
        (r#"doas terraform apply"#, PolicyGateAction::Apply),
        (r#"su -c git merge main"#, PolicyGateAction::Merge),
        (r#"su -c docker push img"#, PolicyGateAction::Deploy),
        (r#"su -c terraform apply"#, PolicyGateAction::Apply),
        (r#"eval 'git merge main'"#, PolicyGateAction::Merge),
        (r#"eval "git push""#, PolicyGateAction::Deploy),
        (r#"eval $(echo git merge main)"#, PolicyGateAction::Merge),
        (r#"eval `echo git push`"#, PolicyGateAction::Deploy),
        (r#"$(echo git) merge main"#, PolicyGateAction::Merge),
        (r#"git $(echo merge) main"#, PolicyGateAction::Merge),
        (r#"echo $(git merge main)"#, PolicyGateAction::Merge),
        (r#"$(git merge main)"#, PolicyGateAction::Merge),
        (r#"FOO=$(git merge main)"#, PolicyGateAction::Merge),
        (r#"FOO=$(git push) bar"#, PolicyGateAction::Deploy),
        (r#"$(which git) merge main"#, PolicyGateAction::Merge),
        (r#"echo $(terraform apply)"#, PolicyGateAction::Apply),
        (r#"`echo git` merge main"#, PolicyGateAction::Merge),
        (r#"git `echo merge` main"#, PolicyGateAction::Merge),
        (r#"echo `git merge main`"#, PolicyGateAction::Merge),
        (r#"`git merge main`"#, PolicyGateAction::Merge),
        (r#"FOO=`git push` bar"#, PolicyGateAction::Deploy),
        (r#"`which git` merge main"#, PolicyGateAction::Merge),
        (r#"echo `kubectl apply -f k.yaml`"#, PolicyGateAction::Apply),
        (r#"bash <<EOF
git merge main
EOF"#, PolicyGateAction::Merge),
        (r#"sh -c 'git merge main' <<EOF
EOF"#, PolicyGateAction::Merge),
        (r#"cat <<EOF | sh
git merge main
EOF"#, PolicyGateAction::Merge),
        (r#"cat <<'EOF' | bash
git merge main
EOF"#, PolicyGateAction::Merge),
        (r#"zsh <<EOF
git push
EOF"#, PolicyGateAction::Deploy),
        (r#"git merge main &|"#, PolicyGateAction::Merge),
        (r#"git merge main > /dev/null"#, PolicyGateAction::Merge),
        (r#"git merge main &> /dev/null"#, PolicyGateAction::Merge),
        (r#"env FOO=bar; git merge main"#, PolicyGateAction::Merge),
        (r#"git merge main; echo done"#, PolicyGateAction::Merge),
        (r#"git merge main && echo done"#, PolicyGateAction::Merge),
        (r#"echo start || git merge main"#, PolicyGateAction::Merge),
        (r#"git merge main | tee out.log"#, PolicyGateAction::Merge),
        (r#"{ git merge main; }"#, PolicyGateAction::Merge),
        (r#"(git merge main)"#, PolicyGateAction::Merge),
        (r#"echo main | xargs git merge"#, PolicyGateAction::Merge),
        (r#"echo main | xargs -t git merge"#, PolicyGateAction::Merge),
        (r#"echo main | xargs -I{} git merge {}"#, PolicyGateAction::Merge),
        (r#"find . -name '*.txt' | xargs git push"#, PolicyGateAction::Deploy),
        (r#"xargs -0 git merge < file"#, PolicyGateAction::Merge),
        (r#"xargs --null git merge < file"#, PolicyGateAction::Merge),
        (r#"xargs -P 4 git push"#, PolicyGateAction::Deploy),
        (r#"find . -exec git merge main \;"#, PolicyGateAction::Merge),
        (r#"find . -exec git push origin main {} +"#, PolicyGateAction::Deploy),
        (r#"find . -type f -execdir git merge main \;"#, PolicyGateAction::Merge),
        (r#"find . -name '*.yaml' -exec kubectl apply -f {} \;"#, PolicyGateAction::Apply),
        (r#"git -c alias.m=merge m main"#, PolicyGateAction::Merge),
        (r#"git --git-dir=.git merge main"#, PolicyGateAction::Merge),
        (r#"git --work-tree=. merge main"#, PolicyGateAction::Merge),
        (r#"git -C /tmp merge main"#, PolicyGateAction::Merge),
        (r#"git --namespace=foo merge main"#, PolicyGateAction::Merge),
        (r#"kubectl plugin apply -f foo.yaml"#, PolicyGateAction::Apply),
        (r#"kubectl kustomize apply"#, PolicyGateAction::Apply),
        (r#"kubectl --server=foo apply -f bar"#, PolicyGateAction::Apply),
        (r#"kubectl --token=foo apply -f bar"#, PolicyGateAction::Apply),
        (r#"terraform --chdir=infra apply"#, PolicyGateAction::Apply),
        (r#"g\i\t m\e\r\g\e main"#, PolicyGateAction::Merge),
        (r#""g"i"t" 'm'e'r'g'e' main"#, PolicyGateAction::Merge),
        (r#"git m"e"rge main"#, PolicyGateAction::Merge),
        (r#"git m\erge main"#, PolicyGateAction::Merge),
        (r#"g''i""t merge main"#, PolicyGateAction::Merge),
        (r#"sudo nohup timeout 10 git merge main"#, PolicyGateAction::Merge),
        (r#"env FOO=bar xargs -I{} sudo git merge {}"#, PolicyGateAction::Merge),
        (r#"bash -c "sudo git merge main""#, PolicyGateAction::Merge),
        (r#"sh -c 'nohup git merge main'"#, PolicyGateAction::Merge),
        (r#"eval "$(echo sudo git merge main)""#, PolicyGateAction::Merge),
Total: 133
