//! Action Registry — static data only.
//!
//! Types, context logic, and query helpers live in `action_ids.rs`.

pub use crate::action_ids::{
    ActionContext, ActionId, ActionSpec, KeyChord,
    footer_specs, spec_by_slash_alias, specs_for_context,
};
use crate::action_ids::always_available;

/// Static registry of all action specs. Single source of truth.
pub static ACTION_SPECS: &[ActionSpec] = &[
    ActionSpec {
        id: ActionId::Quit,
        title: "Quit",
        description: "Quit the application",
        scope: ActionContext::Global,
        keybindings: &["Ctrl+C×2"],
        slash_aliases: &["/quit"],
        palette_visible: true,
        footer_visible: false,
        availability: always_available,
        activity_message: None,
    },
    ActionSpec {
        id: ActionId::OpenCommandPalette,
        title: "Command Palette",
        description: "Open the command palette",
        scope: ActionContext::Global,
        keybindings: &["Ctrl+P"],
        slash_aliases: &[],
        palette_visible: false,
        footer_visible: true,
        availability: always_available,
        activity_message: None,
    },
    ActionSpec {
        id: ActionId::OpenShortcuts,
        title: "Shortcuts",
        description: "Show keyboard shortcuts",
        scope: ActionContext::Global,
        keybindings: &["?"],
        slash_aliases: &["/help"],
        palette_visible: true,
        footer_visible: true,
        availability: always_available,
        activity_message: None,
    },
    ActionSpec {
        id: ActionId::OpenFileSearch,
        title: "File Search",
        description: "Search and insert a file path",
        scope: ActionContext::Global,
        keybindings: &["Ctrl+F"],
        slash_aliases: &["/files"],
        palette_visible: true,
        footer_visible: false,
        availability: always_available,
        activity_message: None,
    },
    ActionSpec {
        id: ActionId::CancelStream,
        title: "Cancel",
        description: "Cancel the current streaming response",
        scope: ActionContext::Global,
        keybindings: &["Ctrl+C"],
        slash_aliases: &[],
        palette_visible: false,
        footer_visible: true,
        availability: |s| s.is_streaming,
        activity_message: None,
    },
    ActionSpec {
        id: ActionId::SwitchModel,
        title: "Switch Model",
        description: "Switch the active language model",
        scope: ActionContext::Global,
        keybindings: &[],
        slash_aliases: &["/model"],
        palette_visible: true,
        footer_visible: false,
        availability: always_available,
        activity_message: None,
    },
    ActionSpec {
        id: ActionId::SwitchProfile,
        title: "Switch Profile",
        description: "Switch configuration profile",
        scope: ActionContext::Global,
        keybindings: &[],
        slash_aliases: &["/profile"],
        palette_visible: true,
        footer_visible: false,
        availability: always_available,
        activity_message: None,
    },
    ActionSpec {
        id: ActionId::SwitchIsolation,
        title: "Switch Isolation",
        description: "Change execution isolation mode",
        scope: ActionContext::Global,
        keybindings: &[],
        slash_aliases: &["/isolation"],
        palette_visible: true,
        footer_visible: false,
        availability: always_available,
        activity_message: None,
    },
    ActionSpec {
        id: ActionId::SwitchRulebook,
        title: "Switch Rulebook",
        description: "Change active rulebooks",
        scope: ActionContext::Global,
        keybindings: &[],
        slash_aliases: &["/rulebook"],
        palette_visible: true,
        footer_visible: false,
        availability: always_available,
        activity_message: None,
    },
    // Workbench — Approvals
    ActionSpec {
        id: ActionId::ApproveCurrent,
        title: "Approve",
        description: "Approve the selected tool call",
        scope: ActionContext::WorkbenchApprovals,
        keybindings: &["a", "Enter"],
        slash_aliases: &[],
        palette_visible: false,
        footer_visible: true,
        availability: |s| !s.pending_approvals.is_empty(),
        activity_message: None,
    },
    ActionSpec {
        id: ActionId::ApproveAll,
        title: "Approve All",
        description: "Approve all pending tool calls",
        scope: ActionContext::WorkbenchApprovals,
        keybindings: &["A"],
        slash_aliases: &[],
        palette_visible: false,
        footer_visible: true,
        availability: |s| !s.pending_approvals.is_empty(),
        activity_message: None,
    },
    ActionSpec {
        id: ActionId::RejectCurrent,
        title: "Reject",
        description: "Reject the selected tool call",
        scope: ActionContext::WorkbenchApprovals,
        keybindings: &["x"],
        slash_aliases: &[],
        palette_visible: false,
        footer_visible: true,
        availability: |s| !s.pending_approvals.is_empty(),
        activity_message: None,
    },
    // Workbench — Review
    ActionSpec {
        id: ActionId::ToggleDiff,
        title: "Diff",
        description: "Toggle diff view for selected file",
        scope: ActionContext::WorkbenchReview,
        keybindings: &["Enter"],
        slash_aliases: &[],
        palette_visible: false,
        footer_visible: true,
        availability: always_available,
        activity_message: None,
    },
    ActionSpec {
        id: ActionId::RevertSelected,
        title: "Revert",
        description: "Revert selected file to snapshot",
        scope: ActionContext::WorkbenchReview,
        keybindings: &["Ctrl+X"],
        slash_aliases: &[],
        palette_visible: false,
        footer_visible: true,
        availability: always_available,
        activity_message: None,
    },
    ActionSpec {
        id: ActionId::RevertAll,
        title: "Revert All",
        description: "Revert all modified files",
        scope: ActionContext::WorkbenchReview,
        keybindings: &["Ctrl+Z"],
        slash_aliases: &[],
        palette_visible: false,
        footer_visible: false,
        availability: always_available,
        activity_message: None,
    },
    // Workbench — Sessions
    ActionSpec {
        id: ActionId::ResumeCheckpoint,
        title: "Resume",
        description: "Resume session from checkpoint",
        scope: ActionContext::WorkbenchSessions,
        keybindings: &["Ctrl+R"],
        slash_aliases: &["/resume"],
        palette_visible: true,
        footer_visible: true,
        availability: always_available,
        activity_message: None,
    },
    ActionSpec {
        id: ActionId::SwitchToSession,
        title: "Switch",
        description: "Switch to selected session",
        scope: ActionContext::WorkbenchSessions,
        keybindings: &["Enter"],
        slash_aliases: &[],
        palette_visible: false,
        footer_visible: true,
        availability: always_available,
        activity_message: None,
    },
    // Workbench — Runtime
    ActionSpec {
        id: ActionId::RefreshRuntime,
        title: "Refresh",
        description: "Refresh runtime job list",
        scope: ActionContext::WorkbenchRuntime,
        keybindings: &["r"],
        slash_aliases: &[],
        palette_visible: false,
        footer_visible: true,
        availability: always_available,
        activity_message: None,
    },
    ActionSpec {
        id: ActionId::CancelRuntimeJob,
        title: "Cancel Job",
        description: "Cancel selected runtime job",
        scope: ActionContext::WorkbenchRuntime,
        keybindings: &["c"],
        slash_aliases: &[],
        palette_visible: false,
        footer_visible: true,
        availability: always_available,
        activity_message: None,
    },
    // Workbench — Plan
    ActionSpec {
        id: ActionId::OpenPlan,
        title: "Plan",
        description: "Open or create plan.md in the Plan workbench",
        scope: ActionContext::Global,
        keybindings: &[],
        slash_aliases: &["/plan"],
        palette_visible: true,
        footer_visible: false,
        availability: always_available,
        activity_message: None,
    },
    ActionSpec {
        id: ActionId::ApprovePlan,
        title: "Approve Plan",
        description: "Approve the current plan and send to agent",
        scope: ActionContext::WorkbenchPlan,
        keybindings: &["a"],
        slash_aliases: &[],
        palette_visible: false,
        footer_visible: true,
        availability: |s| s.plan.mode_active,
        activity_message: None,
    },
    ActionSpec {
        id: ActionId::EditPlan,
        title: "Edit Plan",
        description: "Open plan in external editor",
        scope: ActionContext::WorkbenchPlan,
        keybindings: &["e"],
        slash_aliases: &["/plan-edit"],
        palette_visible: true,
        footer_visible: true,
        availability: always_available,
        activity_message: None,
    },
    ActionSpec {
        id: ActionId::OpenPlanReview,
        title: "Plan Review",
        description: "Review the current plan",
        scope: ActionContext::Global,
        keybindings: &[],
        slash_aliases: &["/plan-review"],
        palette_visible: true,
        footer_visible: false,
        availability: always_available,
        activity_message: None,
    },
    // Workbench — VIL
    ActionSpec {
        id: ActionId::RunRepair,
        title: "Repair",
        description: "Run VIL repair on codebase",
        scope: ActionContext::WorkbenchVil,
        keybindings: &["R"],
        slash_aliases: &["/repair"],
        palette_visible: true,
        footer_visible: true,
        availability: always_available,
        activity_message: None,
    },
    ActionSpec {
        id: ActionId::RunAudit,
        title: "Audit",
        description: "Run VIL audit",
        scope: ActionContext::WorkbenchVil,
        keybindings: &["A"],
        slash_aliases: &[],
        palette_visible: false,
        footer_visible: true,
        availability: always_available,
        activity_message: None,
    },
    // Workbench — tab navigation
    ActionSpec {
        id: ActionId::CycleWorkbenchTab,
        title: "Next Tab",
        description: "Cycle to the next workbench tab",
        scope: ActionContext::WorkbenchAny,
        keybindings: &["Tab"],
        slash_aliases: &[],
        palette_visible: false,
        footer_visible: true,
        availability: |s| s.focus == crate::app::WorkspaceFocus::Workbench,
        activity_message: None,
    },
    // Slash-command actions
    ActionSpec {
        id: ActionId::Clear,
        title: "Clear",
        description: "Clear the conversation",
        scope: ActionContext::Global,
        keybindings: &[],
        slash_aliases: &["/clear"],
        palette_visible: true,
        footer_visible: false,
        availability: always_available,
        activity_message: None,
    },
    ActionSpec {
        id: ActionId::Sessions,
        title: "Sessions",
        description: "Open the sessions workbench tab",
        scope: ActionContext::Global,
        keybindings: &[],
        slash_aliases: &["/sessions"],
        palette_visible: true,
        footer_visible: false,
        availability: always_available,
        activity_message: None,
    },
    ActionSpec {
        id: ActionId::Runtime,
        title: "Runtime",
        description: "Open the runtime jobs tab",
        scope: ActionContext::Global,
        keybindings: &[],
        slash_aliases: &["/runtime"],
        palette_visible: true,
        footer_visible: false,
        availability: always_available,
        activity_message: None,
    },
    ActionSpec {
        id: ActionId::Agents,
        title: "Agents",
        description: "Open the agents scheduler tab",
        scope: ActionContext::Global,
        keybindings: &[],
        slash_aliases: &["/agents"],
        palette_visible: true,
        footer_visible: false,
        availability: always_available,
        activity_message: None,
    },
    ActionSpec {
        id: ActionId::Vwfd,
        title: "VWFD",
        description: "Open the VWFD inspector tab (optionally load a .vwfd.yaml path)",
        scope: ActionContext::Global,
        keybindings: &[],
        slash_aliases: &["/vwfd"],
        palette_visible: true,
        footer_visible: false,
        availability: always_available,
        activity_message: None,
    },
    ActionSpec {
        id: ActionId::Shell,
        title: "Shell",
        description: "Execute a shell command",
        scope: ActionContext::Global,
        keybindings: &[],
        slash_aliases: &["/shell"],
        palette_visible: true,
        footer_visible: false,
        availability: always_available,
        activity_message: None,
    },
    ActionSpec {
        id: ActionId::ShellFocus,
        title: "Shell Focus",
        description: "Bring backgrounded shell to foreground",
        scope: ActionContext::Global,
        keybindings: &[],
        slash_aliases: &["/shell-focus"],
        palette_visible: false,
        footer_visible: false,
        availability: always_available,
        activity_message: None,
    },
    ActionSpec {
        id: ActionId::ShellBackground,
        title: "Shell Background",
        description: "Background the active shell session",
        scope: ActionContext::Global,
        keybindings: &[],
        slash_aliases: &["/shell-bg"],
        palette_visible: false,
        footer_visible: false,
        availability: always_available,
        activity_message: None,
    },
    ActionSpec {
        id: ActionId::ShellKill,
        title: "Shell Kill",
        description: "Kill the active shell session",
        scope: ActionContext::Global,
        keybindings: &[],
        slash_aliases: &["/shell-kill"],
        palette_visible: false,
        footer_visible: false,
        availability: always_available,
        activity_message: None,
    },
    ActionSpec {
        id: ActionId::Context,
        title: "Context",
        description: "Pin a file into context",
        scope: ActionContext::Global,
        keybindings: &[],
        slash_aliases: &["/context"],
        palette_visible: true,
        footer_visible: false,
        availability: always_available,
        activity_message: None,
    },
    ActionSpec {
        id: ActionId::NewSession,
        title: "New Session",
        description: "Start a new session",
        scope: ActionContext::Global,
        keybindings: &[],
        slash_aliases: &["/new"],
        palette_visible: true,
        footer_visible: false,
        availability: always_available,
        activity_message: None,
    },
    ActionSpec {
        id: ActionId::Export,
        title: "Export",
        description: "Export session bundle",
        scope: ActionContext::Global,
        keybindings: &[],
        slash_aliases: &["/export"],
        palette_visible: true,
        footer_visible: false,
        availability: always_available,
        activity_message: None,
    },
    ActionSpec {
        id: ActionId::Import,
        title: "Import",
        description: "Import session bundle",
        scope: ActionContext::Global,
        keybindings: &[],
        slash_aliases: &["/import"],
        palette_visible: true,
        footer_visible: false,
        availability: always_available,
        activity_message: None,
    },
    ActionSpec {
        id: ActionId::ReviewOpen,
        title: "Review",
        description: "Open the git review overlay",
        scope: ActionContext::Global,
        keybindings: &[],
        slash_aliases: &["/review"],
        palette_visible: true,
        footer_visible: false,
        availability: always_available,
        activity_message: None,
    },
    ActionSpec {
        id: ActionId::Changes,
        title: "Changes",
        description: "Open the changeset overlay",
        scope: ActionContext::Global,
        keybindings: &[],
        slash_aliases: &["/changes"],
        palette_visible: true,
        footer_visible: false,
        availability: always_available,
        activity_message: None,
    },
    ActionSpec {
        id: ActionId::FileChanges,
        title: "File Changes",
        description: "Open the file changes overlay",
        scope: ActionContext::Global,
        keybindings: &[],
        slash_aliases: &["/file-changes"],
        palette_visible: true,
        footer_visible: false,
        availability: always_available,
        activity_message: None,
    },
    // Overlay — generic close
    ActionSpec {
        id: ActionId::CloseOverlay,
        title: "Close",
        description: "Close the active overlay",
        scope: ActionContext::OverlayActive,
        keybindings: &["Esc"],
        slash_aliases: &[],
        palette_visible: false,
        footer_visible: true,
        availability: |s| s.overlay_manager.any_active(),
        activity_message: None,
    },
    // Wave 2 overlays
    ActionSpec {
        id: ActionId::OpenTaskTray,
        title: "Task Tray",
        description: "Open background task tray",
        scope: ActionContext::Global,
        keybindings: &["Ctrl+T"],
        slash_aliases: &["/tasks"],
        palette_visible: true,
        footer_visible: false,
        availability: |_| true,
        activity_message: None,
    },
    ActionSpec {
        id: ActionId::OpenThemePicker,
        title: "Theme Picker",
        description: "Switch color theme",
        scope: ActionContext::Global,
        keybindings: &["Ctrl+Shift+T"],
        slash_aliases: &["/theme"],
        palette_visible: true,
        footer_visible: false,
        availability: |_| true,
        activity_message: None,
    },
    ActionSpec {
        id: ActionId::OpenFilePicker,
        title: "File Picker",
        description: "Open file picker (multi-select, preview)",
        scope: ActionContext::Global,
        keybindings: &["Ctrl+P"],
        slash_aliases: &["/pick"],
        palette_visible: true,
        footer_visible: false,
        availability: |_| true,
        activity_message: None,
    },
    ActionSpec {
        id: ActionId::OpenSessionResume,
        title: "Resume Session",
        description: "Fuzzy-search and resume a previous session",
        scope: ActionContext::Global,
        keybindings: &["Ctrl+R"],
        slash_aliases: &["/sessions-resume"],
        palette_visible: true,
        footer_visible: false,
        availability: |_| true,
        activity_message: None,
    },
];
