//! Action Registry — static data only.
//!
//! Types, context logic, and query helpers live in `action_ids.rs`.

use crate::action_ids::always_available;
pub use crate::action_ids::{
    ActionContext, ActionId, ActionSpec, KeyChord, footer_specs, spec_by_slash_alias,
    specs_for_context,
};

/// Static registry of all action specs. Single source of truth.
pub static ACTION_SPECS: &[ActionSpec] = &[
    ActionSpec {
        id: ActionId::Quit,
        title: "Quit",
        description: "Quit the application",
        scope: ActionContext::Global,
        keybindings: &["Ctrl+C×2"],
        slash_aliases: &["/quit"],
        palette_visible: true,
        footer_visible: false,
        availability: always_available,
        activity_message: None,
    },
    ActionSpec {
        id: ActionId::OpenCommandPalette,
        title: "Command Palette",
        description: "Open the command palette",
        scope: ActionContext::Global,
        keybindings: &["Ctrl+P"],
        slash_aliases: &[],
        palette_visible: false,
        footer_visible: true,
        availability: always_available,
        activity_message: None,
    },
    ActionSpec {
        id: ActionId::OpenShortcuts,
        title: "Shortcuts",
        description: "Show keyboard shortcuts",
        scope: ActionContext::Global,
        keybindings: &["?"],
        slash_aliases: &["/help"],
        palette_visible: true,
        footer_visible: true,
        availability: always_available,
        activity_message: None,
    },
    ActionSpec {
        id: ActionId::OpenFileSearch,
        title: "File Search",
        description: "Search and insert a file path",
        scope: ActionContext::Global,
        keybindings: &["Ctrl+F"],
        slash_aliases: &["/files"],
        palette_visible: true,
        footer_visible: false,
        availability: always_available,
        activity_message: None,
    },
    ActionSpec {
        id: ActionId::CancelStream,
        title: "Cancel",
        description: "Cancel the current streaming response",
        scope: ActionContext::Global,
        keybindings: &["Ctrl+C"],
        slash_aliases: &[],
        palette_visible: false,
        footer_visible: true,
        availability: |s| s.transcript.streaming.is_streaming,
        activity_message: None,
    },
    ActionSpec {
        id: ActionId::SwitchModel,
        title: "Switch Model",
        description: "Switch the active language model",
        scope: ActionContext::Global,
        keybindings: &[],
        slash_aliases: &["/model"],
        palette_visible: true,
        footer_visible: false,
        availability: always_available,
        activity_message: None,
    },
    ActionSpec {
        id: ActionId::SwitchProfile,
        title: "Switch Profile",
        description: "Switch configuration profile",
        scope: ActionContext::Global,
        keybindings: &[],
        slash_aliases: &["/profile"],
        palette_visible: true,
        footer_visible: false,
        availability: always_available,
        activity_message: None,
    },
    ActionSpec {
        id: ActionId::SwitchIsolation,
        title: "Switch Isolation",
        description: "Change execution isolation mode",
        scope: ActionContext::Global,
        keybindings: &[],
        slash_aliases: &["/isolation"],
        palette_visible: true,
        footer_visible: false,
        availability: always_available,
        activity_message: None,
    },
    ActionSpec {
        id: ActionId::SwitchRulebook,
        title: "Switch Rulebook",
        description: "Change active rulebooks",
        scope: ActionContext::Global,
        keybindings: &[],
        slash_aliases: &["/rulebook"],
        palette_visible: true,
        footer_visible: false,
        availability: always_available,
        activity_message: None,
    },
    // Workbench — Approvals
    ActionSpec {
        id: ActionId::ApproveCurrent,
        title: "Approve",
        description: "Approve the selected tool call",
        scope: ActionContext::WorkbenchApprovals,
        keybindings: &["a", "Enter"],
        slash_aliases: &[],
        palette_visible: false,
        footer_visible: true,
        availability: |s| !s.execution.approvals.pending_approvals.is_empty(),
        activity_message: None,
    },
    ActionSpec {
        id: ActionId::ApproveAll,
        title: "Approve All",
        description: "Approve all pending tool calls",
        scope: ActionContext::WorkbenchApprovals,
        keybindings: &["A"],
        slash_aliases: &[],
        palette_visible: false,
        footer_visible: true,
        availability: |s| !s.execution.approvals.pending_approvals.is_empty(),
        activity_message: None,
    },
    ActionSpec {
        id: ActionId::RejectCurrent,
        title: "Reject",
        description: "Reject the selected tool call",
        scope: ActionContext::WorkbenchApprovals,
        keybindings: &["x"],
        slash_aliases: &[],
        palette_visible: false,
        footer_visible: true,
        availability: |s| !s.execution.approvals.pending_approvals.is_empty(),
        activity_message: None,
    },
    // Workbench — Review
    ActionSpec {
        id: ActionId::ToggleDiff,
        title: "Diff",
        description: "Toggle diff view for selected file",
        scope: ActionContext::WorkbenchReview,
        keybindings: &["Enter"],
        slash_aliases: &[],
        palette_visible: false,
        footer_visible: true,
        availability: always_available,
        activity_message: None,
    },
    ActionSpec {
        id: ActionId::RevertSelected,
        title: "Revert",
        description: "Revert selected file to snapshot",
        scope: ActionContext::WorkbenchReview,
        keybindings: &["Ctrl+X"],
        slash_aliases: &[],
        palette_visible: false,
        footer_visible: true,
        availability: always_available,
        activity_message: None,
    },
    ActionSpec {
        id: ActionId::RevertAll,
        title: "Revert All",
        description: "Revert all modified files",
        scope: ActionContext::WorkbenchReview,
        keybindings: &["Ctrl+Z"],
        slash_aliases: &[],
        palette_visible: false,
        footer_visible: false,
        availability: always_available,
        activity_message: None,
    },
    // Workbench — Sessions
    ActionSpec {
        id: ActionId::ResumeCheckpoint,
        title: "Resume",
        description: "Resume session from checkpoint",
        scope: ActionContext::WorkbenchSessions,
        keybindings: &["Ctrl+R"],
        slash_aliases: &["/resume"],
        palette_visible: true,
        footer_visible: true,
        availability: always_available,
        activity_message: None,
    },
    ActionSpec {
        id: ActionId::SwitchToSession,
        title: "Switch",
        description: "Switch to selected session",
        scope: ActionContext::WorkbenchSessions,
        keybindings: &["Enter"],
        slash_aliases: &[],
        palette_visible: false,
        footer_visible: true,
        availability: always_available,
        activity_message: None,
    },
    // Workbench — Runtime
    ActionSpec {
        id: ActionId::RefreshRuntime,
        title: "Refresh",
        description: "Refresh runtime job list",
        scope: ActionContext::WorkbenchRuntime,
        keybindings: &["r"],
        slash_aliases: &[],
        palette_visible: false,
        footer_visible: true,
        availability: always_available,
        activity_message: None,
    },
    ActionSpec {
        id: ActionId::CancelRuntimeJob,
        title: "Cancel Job",
        description: "Cancel selected runtime job",
        scope: ActionContext::WorkbenchRuntime,
        keybindings: &["c"],
        slash_aliases: &[],
        palette_visible: false,
        footer_visible: true,
        availability: always_available,
        activity_message: None,
    },
    // Workbench — Plan
    ActionSpec {
        id: ActionId::OpenPlan,
        title: "Plan",
        description: "Open or create plan.md in the Plan workbench",
        scope: ActionContext::Global,
        keybindings: &[],
        slash_aliases: &["/plan"],
        palette_visible: true,
        footer_visible: false,
        availability: always_available,
        activity_message: None,
    },
    ActionSpec {
        id: ActionId::ApprovePlan,
        title: "Approve Plan",
        description: "Approve the current plan and send to agent",
        scope: ActionContext::WorkbenchPlan,
        keybindings: &["a"],
        slash_aliases: &[],
        palette_visible: false,
        footer_visible: true,
        availability: |s| s.workspace.plan.mode_active,
        activity_message: None,
    },
    ActionSpec {
        id: ActionId::EditPlan,
        title: "Edit Plan",
        description: "Open plan in external editor",
        scope: ActionContext::WorkbenchPlan,
        keybindings: &["e"],
        slash_aliases: &["/plan-edit"],
        palette_visible: true,
        footer_visible: true,
        availability: always_available,
        activity_message: None,
    },
    ActionSpec {
        id: ActionId::OpenPlanReview,
        title: "Plan Review",
        description: "Review the current plan",
        scope: ActionContext::Global,
        keybindings: &[],
        slash_aliases: &["/plan-review"],
        palette_visible: true,
        footer_visible: false,
        availability: always_available,
        activity_message: None,
    },
    // Workbench — VIL
    ActionSpec {
        id: ActionId::RunRepair,
        title: "Repair",
        description: "Run VIL repair on codebase",
        scope: ActionContext::WorkbenchVil,
        keybindings: &["R"],
        slash_aliases: &["/repair"],
        palette_visible: true,
        footer_visible: true,
        availability: always_available,
        activity_message: None,
    },
    ActionSpec {
        id: ActionId::RunAudit,
        title: "Audit",
        description: "Run VIL audit",
        scope: ActionContext::WorkbenchVil,
        keybindings: &["A"],
        slash_aliases: &[],
        palette_visible: false,
        footer_visible: true,
        availability: always_available,
        activity_message: None,
    },
    // Workbench — tab navigation
    ActionSpec {
        id: ActionId::CycleWorkbenchTab,
        title: "Next Tab",
        description: "Cycle to the next workbench tab",
        scope: ActionContext::WorkbenchAny,
        keybindings: &["Tab"],
        slash_aliases: &[],
        palette_visible: false,
        footer_visible: true,
        availability: |s| s.layout.focus == crate::app::WorkspaceFocus::Workbench,
        activity_message: None,
    },
    // Slash-command actions
    ActionSpec {
        id: ActionId::Clear,
        title: "Clear",
        description: "Clear the conversation",
        scope: ActionContext::Global,
        keybindings: &[],
        slash_aliases: &["/clear"],
        palette_visible: true,
        footer_visible: false,
        availability: always_available,
        activity_message: None,
    },
    ActionSpec {
        id: ActionId::Sessions,
        title: "Sessions",
        description: "Open the sessions workbench tab",
        scope: ActionContext::Global,
        keybindings: &[],
        slash_aliases: &["/sessions"],
        palette_visible: true,
        footer_visible: false,
        availability: always_available,
        activity_message: None,
    },
    ActionSpec {
        id: ActionId::Runtime,
        title: "Runtime",
        description: "Open the runtime jobs tab",
        scope: ActionContext::Global,
        keybindings: &[],
        slash_aliases: &["/runtime"],
        palette_visible: true,
        footer_visible: false,
        availability: always_available,
        activity_message: None,
    },
    ActionSpec {
        id: ActionId::Agents,
        title: "Agents",
        description: "Open the agents scheduler tab",
        scope: ActionContext::Global,
        keybindings: &[],
        slash_aliases: &["/agents"],
        palette_visible: true,
        footer_visible: false,
        availability: always_available,
        activity_message: None,
    },
    ActionSpec {
        id: ActionId::Vwfd,
        title: "VWFD",
        description: "Open the VWFD inspector tab (optionally load a .vwfd.yaml path)",
        scope: ActionContext::Global,
        keybindings: &[],
        slash_aliases: &["/vwfd"],
        palette_visible: true,
        footer_visible: false,
        availability: always_available,
        activity_message: None,
    },
    ActionSpec {
        id: ActionId::Shell,
        title: "Shell",
        description: "Execute a shell command",
        scope: ActionContext::Global,
        keybindings: &[],
        slash_aliases: &["/shell"],
        palette_visible: true,
        footer_visible: false,
        availability: always_available,
        activity_message: None,
    },
    ActionSpec {
        id: ActionId::ShellFocus,
        title: "Shell Focus",
        description: "Bring backgrounded shell to foreground",
        scope: ActionContext::Global,
        keybindings: &[],
        slash_aliases: &["/shell-focus"],
        palette_visible: false,
        footer_visible: false,
        availability: always_available,
        activity_message: None,
    },
    ActionSpec {
        id: ActionId::ShellBackground,
        title: "Shell Background",
        description: "Background the active shell session",
        scope: ActionContext::Global,
        keybindings: &[],
        slash_aliases: &["/shell-bg"],
        palette_visible: false,
        footer_visible: false,
        availability: always_available,
        activity_message: None,
    },
    ActionSpec {
        id: ActionId::ShellKill,
        title: "Shell Kill",
        description: "Kill the active shell session",
        scope: ActionContext::Global,
        keybindings: &[],
        slash_aliases: &["/shell-kill"],
        palette_visible: false,
        footer_visible: false,
        availability: always_available,
        activity_message: None,
    },
    ActionSpec {
        id: ActionId::Context,
        title: "Context",
        description: "Pin a file into context",
        scope: ActionContext::Global,
        keybindings: &[],
        slash_aliases: &["/context"],
        palette_visible: true,
        footer_visible: false,
        availability: always_available,
        activity_message: None,
    },
    ActionSpec {
        id: ActionId::NewSession,
        title: "New Session",
        description: "Start a new session",
        scope: ActionContext::Global,
        keybindings: &[],
        slash_aliases: &["/new"],
        palette_visible: true,
        footer_visible: false,
        availability: always_available,
        activity_message: None,
    },
    ActionSpec {
        id: ActionId::Export,
        title: "Export",
        description: "Export session bundle",
        scope: ActionContext::Global,
        keybindings: &[],
        slash_aliases: &["/export"],
        palette_visible: true,
        footer_visible: false,
        availability: always_available,
        activity_message: None,
    },
    ActionSpec {
        id: ActionId::Import,
        title: "Import",
        description: "Import session bundle",
        scope: ActionContext::Global,
        keybindings: &[],
        slash_aliases: &["/import"],
        palette_visible: true,
        footer_visible: false,
        availability: always_available,
        activity_message: None,
    },
    ActionSpec {
        id: ActionId::ReviewOpen,
        title: "Review",
        description: "Open the git review overlay",
        scope: ActionContext::Global,
        keybindings: &[],
        slash_aliases: &["/review"],
        palette_visible: true,
        footer_visible: false,
        availability: always_available,
        activity_message: None,
    },
    ActionSpec {
        id: ActionId::Changes,
        title: "Changes",
        description: "Open the changeset overlay",
        scope: ActionContext::Global,
        keybindings: &[],
        slash_aliases: &["/changes"],
        palette_visible: true,
        footer_visible: false,
        availability: always_available,
        activity_message: None,
    },
    ActionSpec {
        id: ActionId::FileChanges,
        title: "File Changes",
        description: "Open the file changes overlay",
        scope: ActionContext::Global,
        keybindings: &[],
        slash_aliases: &["/file-changes"],
        palette_visible: true,
        footer_visible: false,
        availability: always_available,
        activity_message: None,
    },
    // Overlay — generic close
    ActionSpec {
        id: ActionId::CloseOverlay,
        title: "Close",
        description: "Close the active overlay",
        scope: ActionContext::OverlayActive,
        keybindings: &["Esc"],
        slash_aliases: &[],
        palette_visible: false,
        footer_visible: true,
        availability: |s| s.layout.overlay_manager.any_active(),
        activity_message: None,
    },
    // Wave 2 overlays
    ActionSpec {
        id: ActionId::OpenTaskTray,
        title: "Task Tray",
        description: "Open background task tray",
        scope: ActionContext::Global,
        keybindings: &["Ctrl+T"],
        slash_aliases: &["/tasks"],
        palette_visible: true,
        footer_visible: false,
        availability: |_| true,
        activity_message: None,
    },
    ActionSpec {
        id: ActionId::OpenThemePicker,
        title: "Theme Picker",
        description: "Switch color theme",
        scope: ActionContext::Global,
        keybindings: &["Ctrl+Shift+T"],
        slash_aliases: &["/theme"],
        palette_visible: true,
        footer_visible: false,
        availability: |_| true,
        activity_message: None,
    },
    ActionSpec {
        id: ActionId::OpenFilePicker,
        title: "File Picker",
        description: "Open file picker (multi-select, preview)",
        scope: ActionContext::Global,
        // U0 fix — Ctrl+P previously collided with OpenCommandPalette.
        // File picker moves to Ctrl+Shift+P; command palette keeps
        // Ctrl+P since it is the operator's single front door per
        // the UX unification plan.
        keybindings: &["Ctrl+Shift+P"],
        slash_aliases: &["/pick"],
        palette_visible: true,
        footer_visible: false,
        availability: |_| true,
        activity_message: None,
    },
    ActionSpec {
        id: ActionId::OpenSessionResume,
        title: "Resume Session",
        description: "Fuzzy-search and resume a previous session",
        scope: ActionContext::Global,
        keybindings: &["Ctrl+R"],
        slash_aliases: &["/sessions-resume"],
        palette_visible: true,
        footer_visible: false,
        availability: |_| true,
        activity_message: None,
    },
    // ── Phase B1 — bundled skills exposed via palette ────────────
    ActionSpec {
        id: ActionId::SkillBatch,
        title: "Skill: batch",
        description: "Run a labelled list of steps in one skill call",
        scope: ActionContext::Global,
        keybindings: &[],
        slash_aliases: &["/skill-batch"],
        palette_visible: true,
        footer_visible: false,
        availability: always_available,
        activity_message: None,
    },
    ActionSpec {
        id: ActionId::SkillLoop,
        title: "Skill: loop",
        description: "Schedule a recurring skill invocation",
        scope: ActionContext::Global,
        keybindings: &[],
        slash_aliases: &["/skill-loop"],
        palette_visible: true,
        footer_visible: false,
        availability: always_available,
        activity_message: None,
    },
    ActionSpec {
        id: ActionId::SkillRemember,
        title: "Skill: remember",
        description: "Persist a named memory entry",
        scope: ActionContext::Global,
        keybindings: &[],
        slash_aliases: &["/skill-remember"],
        palette_visible: true,
        footer_visible: false,
        availability: always_available,
        activity_message: None,
    },
    ActionSpec {
        id: ActionId::SkillSimplify,
        title: "Skill: simplify",
        description: "Collapse overlong text to a bounded head-and-tail",
        scope: ActionContext::Global,
        keybindings: &[],
        slash_aliases: &["/skill-simplify"],
        palette_visible: true,
        footer_visible: false,
        availability: always_available,
        activity_message: None,
    },
    ActionSpec {
        id: ActionId::SkillStuck,
        title: "Skill: stuck",
        description: "Detect agent loop from recent tool history",
        scope: ActionContext::Global,
        keybindings: &[],
        slash_aliases: &["/skill-stuck"],
        palette_visible: true,
        footer_visible: false,
        availability: always_available,
        activity_message: None,
    },
    ActionSpec {
        id: ActionId::SkillVerify,
        title: "Skill: verify",
        description: "Self-audit the agent's last mutation",
        scope: ActionContext::Global,
        keybindings: &[],
        slash_aliases: &["/skill-verify"],
        palette_visible: true,
        footer_visible: false,
        availability: always_available,
        activity_message: None,
    },
    // ── Phase F2 — W8 CLI commands as palette entries ────────────
    ActionSpec {
        id: ActionId::SpawnCliAdvisor,
        title: "CLI: advisor",
        description: "Pre-commit snapshot: branch, uncommitted, last commit",
        scope: ActionContext::Global,
        keybindings: &[],
        slash_aliases: &["/advisor"],
        palette_visible: true,
        footer_visible: false,
        availability: always_available,
        activity_message: None,
    },
    ActionSpec {
        id: ActionId::SpawnCliAutofixPr,
        title: "CLI: autofix-pr",
        description: "Lint the unstaged diff for auto-fixable patterns",
        scope: ActionContext::Global,
        keybindings: &[],
        slash_aliases: &["/autofix-pr"],
        palette_visible: true,
        footer_visible: false,
        availability: always_available,
        activity_message: None,
    },
    ActionSpec {
        id: ActionId::SpawnCliBughunter,
        title: "CLI: bughunter",
        description: "Scan the last commit for code smells",
        scope: ActionContext::Global,
        keybindings: &[],
        slash_aliases: &["/bughunter"],
        palette_visible: true,
        footer_visible: false,
        availability: always_available,
        activity_message: None,
    },
    ActionSpec {
        id: ActionId::SpawnCliSecurityReview,
        title: "CLI: security-review",
        description: "Scan staged diff for secret-shaped strings",
        scope: ActionContext::Global,
        keybindings: &[],
        slash_aliases: &["/security-review"],
        palette_visible: true,
        footer_visible: false,
        availability: always_available,
        activity_message: None,
    },
    ActionSpec {
        id: ActionId::SpawnCliPerfIssue,
        title: "CLI: perf-issue",
        description: "Surface large files + slow-test markers",
        scope: ActionContext::Global,
        keybindings: &[],
        slash_aliases: &["/perf-issue"],
        palette_visible: true,
        footer_visible: false,
        availability: always_available,
        activity_message: None,
    },
    ActionSpec {
        id: ActionId::SpawnCliTeleport,
        title: "CLI: teleport",
        description: "Quick session switcher across recent sessions",
        scope: ActionContext::Global,
        keybindings: &[],
        slash_aliases: &["/teleport"],
        palette_visible: true,
        footer_visible: false,
        availability: always_available,
        activity_message: None,
    },
    ActionSpec {
        id: ActionId::SpawnCliThinkback,
        title: "CLI: thinkback",
        description: "Tail the newest session transcript",
        scope: ActionContext::Global,
        keybindings: &[],
        slash_aliases: &["/thinkback"],
        palette_visible: true,
        footer_visible: false,
        availability: always_available,
        activity_message: None,
    },
    ActionSpec {
        id: ActionId::SpawnCliUltraplan,
        title: "CLI: ultraplan",
        description: "Offline plan-skeleton template for a goal",
        scope: ActionContext::Global,
        keybindings: &[],
        slash_aliases: &["/ultraplan"],
        palette_visible: true,
        footer_visible: false,
        availability: always_available,
        activity_message: None,
    },
    ActionSpec {
        id: ActionId::SpawnCliRewind,
        title: "CLI: rewind",
        description: "List resume candidates newest-first",
        scope: ActionContext::Global,
        keybindings: &[],
        slash_aliases: &["/rewind"],
        palette_visible: true,
        footer_visible: false,
        availability: always_available,
        activity_message: None,
    },
    ActionSpec {
        id: ActionId::SpawnCliDecisions,
        title: "CLI: decisions",
        description: "Dump agent-decision trajectory records",
        scope: ActionContext::Global,
        keybindings: &[],
        slash_aliases: &["/decisions"],
        palette_visible: true,
        footer_visible: false,
        availability: always_available,
        activity_message: None,
    },
];
