//! O3 — Empirical first-paint breakdown harness.
//!
//! Measures the sub-operations the TUI runs before the first ratatui
//! frame paints. Writes the timing breakdown both as test output (so
//! `cargo nextest run` surfaces it) and as `docs/boot-timing.md` for
//! historical comparison.

use std::time::Instant;

use vac_core::VacConfig;
use vac_tui_runtime::app::{AppState, AppStateOptions};

struct Timing {
    step: &'static str,
    micros: u128,
}

#[test]
fn first_paint_breakdown_stays_under_budget() {
    let project_root = std::env::temp_dir().join("vac_boot_harness");
    let _ = std::fs::create_dir_all(&project_root);

    let mut timings: Vec<Timing> = Vec::new();

    let t = Instant::now();
    let _cfg = VacConfig::load_with_fallback(&project_root).unwrap_or_default();
    timings.push(Timing {
        step: "VacConfig::load_with_fallback",
        micros: t.elapsed().as_micros(),
    });

    let t = Instant::now();
    let _state = AppState::new(AppStateOptions {
        model: None,
        session_id: None,
        checkpoint_path: None,
        project_root: project_root.clone(),
    });
    timings.push(Timing {
        step: "AppState::new",
        micros: t.elapsed().as_micros(),
    });

    let t = Instant::now();
    let _minimal = VacConfig::minimal();
    timings.push(Timing {
        step: "VacConfig::minimal",
        micros: t.elapsed().as_micros(),
    });

    // Reporting
    let total: u128 = timings.iter().map(|t| t.micros).sum();
    let mut report = String::new();
    report.push_str("# Boot Timing Breakdown\n\n");
    report.push_str("Generated by `cargo nextest run -p vac_tui_runtime --test first_paint_harness`.\n");
    report.push_str("All timings in microseconds on the machine running the test.\n\n");
    report.push_str("| Step | µs |\n|---|---|\n");
    for t in &timings {
        report.push_str(&format!("| `{}` | {} |\n", t.step, t.micros));
    }
    report.push_str(&format!("| **total** | **{total}** |\n\n"));
    report.push_str("Budget: synchronous pre-paint work under 50,000µs (50ms). If total exceeds this, the harness test fails.\n");

    println!("{}", report);
    let _ = std::fs::write("docs/boot-timing.md", &report);

    assert!(
        total < 50_000,
        "total pre-paint work {}µs exceeds 50ms budget",
        total
    );
}
