#:frozen_string_literal: true
#
# NS.7 — Homebrew formula for VAC.
#
# Ship via a tap (e.g. `brew tap vastar/vac`). The release.yml
# workflow writes the resolved `url` + `sha256` below from the
# GitHub Release asset at publish time; this file in the main repo
# is the canonical template.
#
# Operator install:
#   brew tap vastar/vac
#   brew install vac
#
# Verification (minisign already shipped alongside the tarball):
#   brew install minisign
#   minisign -V -p packaging/minisign.pub -m $(brew --prefix vac)/bin/vac

class Vac < Formula
  desc "VAC — Vastar Agentic CLI: Autonomous development CLI built on VIL Engine"
  homepage "https://github.com/IbrohimMid/VAC"
  version "0.1.0"
  license "MIT"

  # NB: These values are overwritten per-release by the bump-formula
  # step in release.yml. The placeholders below let `brew style`
  # pass on the in-repo template.
  if OS.mac?
    if Hardware::CPU.arm?
      url "https://github.com/IbrohimMid/VAC/releases/download/v0.1.0/vac-aarch64-apple-darwin.tar.gz"
      sha256 "0000000000000000000000000000000000000000000000000000000000000000"
    else
      url "https://github.com/IbrohimMid/VAC/releases/download/v0.1.0/vac-x86_64-apple-darwin.tar.gz"
      sha256 "0000000000000000000000000000000000000000000000000000000000000000"
    end
  elsif OS.linux?
    if Hardware::CPU.arm?
      url "https://github.com/IbrohimMid/VAC/releases/download/v0.1.0/vac-aarch64-unknown-linux-gnu.tar.gz"
      sha256 "0000000000000000000000000000000000000000000000000000000000000000"
    else
      url "https://github.com/IbrohimMid/VAC/releases/download/v0.1.0/vac-x86_64-unknown-linux-gnu.tar.gz"
      sha256 "0000000000000000000000000000000000000000000000000000000000000000"
    end
  end

  # Runtime deps: git is needed by enter_worktree + VAC's session
  # diffs. Everything else is statically linked into the binary.
  depends_on "git"

  def install
    bin.install "vac"
    # Shell completions — generated by `vac completions <shell>`.
    # cargo-dist ships them alongside the binary in the release
    # tarball; move them into Homebrew's standard locations.
    if (buildpath/"completions/_vac").exist?
      zsh_completion.install "completions/_vac"
    end
    if (buildpath/"completions/vac.bash").exist?
      bash_completion.install "completions/vac.bash"
    end
    if (buildpath/"completions/vac.fish").exist?
      fish_completion.install "completions/vac.fish"
    end
    # Shipped docs (optional).
    doc.install Dir["docs/*.md"] if File.directory?("docs")
  end

  test do
    assert_match "vac ", shell_output("#{bin}/vac --version")
    # `vac doctor` prints a self-check and exits 0 in a clean env.
    assert_equal 0, system("#{bin}/vac", "doctor")
  end
end
