[package]
name = "vac_changeset"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
description.workspace = true

[dependencies]
indexmap = "2"
serde_json = { workspace = true }
vil_vwfd = { path = "../vil_vwfd" }

[lints]
workspace = true
