[package]
name = "vil_metrics"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
license.workspace = true
description = "VIL Metrics — system metrics collection plugin"

[features]
default = []
vil_integration = []

[dependencies]
tokio = { workspace = true }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
thiserror = { workspace = true }
tracing = { workspace = true }
sysinfo = "0.32"
chrono = { workspace = true, features = ["serde"] }
dashmap = { workspace = true }
async-trait = { workspace = true }

[dev-dependencies]
tokio = { workspace = true, features = ["test-util", "time"] }